Shopizee/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from . import views
from .views import HomeView, DetailsView
from django.conf.urls import url
# from django.contrib.sitemaps.views import sitemap

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('products.urls')),
    path('register/',include('register.urls')),
    path('',HomeView.as_view(), name='index'),
    # path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # AJAX URLS
    path("ajax/details/<int:pk>/",views.DetailsView, name="details"),
    # AJAX URLS   
    path('privacy-policy/',views.PrivacyView, name='privacy-policy'),
    path('terms/',views.PrivacyView, name='terms'),
    path('disclaimer/',views.DisclaimerView, name='disclaimer'),
    path('about/',views.AboutView, name='about'),
    path('contact/',views.ContactView, name='contact'),
]


urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

register/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from register import views
from register.views import UserEditView,PasswordChangeView
from register.forms import ResetPasswordForm
urlpatterns = [
    # path("register",views.register, name='register'),
    path("login",views.login, name='login'),
    path("logout/",views.logout, name='logout'),

    path("my_product/",views.my_blog, name='my_product'),
    path('edit_profile/',UserEditView.as_view(), name='edit_profile'),
    # path('password/',auth_views.PasswordChangeView.as_view(template_name='register/change_password.html')),
    path('password/',PasswordChangeView.as_view(template_name='register/change_password.html'),name='password'),
    
    path('reset_password/',
        auth_views.PasswordResetView.as_view(template_name = 'register/ForgotPassword.html', html_email_template_name='register/password_reset_html_email.html'),
        name="reset_password"),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name = 'register/PasswordResetDone.html'), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name = 'register/PasswordResetConfirm.html'), 
        name="password_reset_confirm"),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name = 'register/PasswordResetComplete.html'), 
        name="password_reset_complete"),

    # AJAX URLS
    path("ajax/delete_account/",views.delete_user, name="delete_account"),
    # AJAX URLS  
]

register/models.py
from django.db import models

# Create your models here.

register/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm

class EditProfileForm(UserChangeForm):
    username = forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class': 'form-control','required':''}))
    first_name = forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control','required':''}))
    # last_name = forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class': 'form-control'}))
    
    class Meta:
        model= User
        fields = ('username','first_name','last_name','email')

class PasswordChangingForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}))
    
    class Meta:
        model= User
        fields = ('old_password','new_password1','new_password2')

class ResetPasswordForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input100', 'type':'password', 'placeholder':'Password'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input100', 'type':'password', 'placeholder':'Confirm Password'}))
    
    class Meta:
        model= User
        fields = ('password','confirm_password')

register/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User, auth
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth.views import PasswordChangeView
from django.views import generic
from register.forms import EditProfileForm, PasswordChangingForm
from django.contrib.admin.views.decorators import staff_member_required
from products.models import Product_Details, ProductImage, Category
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.template.loader import render_to_string
from django.http import HttpResponseRedirect,Http404,JsonResponse

# Create your views here.

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user =auth.authenticate(username=username,password=password)

        if user is not None:
            messages.success(request, 'Login Successful')
            auth.login(request, user)
            return redirect("/")
        else:
            messages.info(request,'The username or password you entered is incorrect')
            return redirect('login')
    else:
        if request.user.is_authenticated:
            return redirect('/')
        else:
            return render(request, 'register/login.html')
            

@login_required(login_url='/')
def logout(request):
    messages.success(request, 'You are successfully logged out')
    auth.logout(request)
    return redirect('/')

@staff_member_required(login_url='/')
def my_blog(request):
    product = Product_Details.objects.all()
    bool = False
    if Product_Details.objects.all():
        bool = True
    else:
        bool = False

    paginator = Paginator(product, 25) # Show 4 contacts per page.

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    cat_menu = Category.objects.all()[:5]
    category = Category.objects.all()[:3]

    return render(request, 'register/my_product.html',{'page_obj': page_obj, 'category':category, 'cat_menu' : cat_menu, 'bool':bool})

class UserEditView(generic.UpdateView):
    form_class = EditProfileForm
    template_name = 'register/edit_profile.html'
    success_url = reverse_lazy('index')
    
    def get_object(self):
        return self.request.user

class PasswordChangeView(PasswordChangeView):
    # form_class = PasswordChangingForm
    form_class = PasswordChangingForm
    success_url = reverse_lazy('index')

@login_required(login_url='/')
def delete_user(request):   
    if request.is_ajax and request.method == "POST" and request.user.is_authenticated == True:
        try:
            delete_user = User.objects.get(username = request.user.username)
            delete_user.delete()
            # messages.success(request, "Account Deleted Successfully")
            html = render_to_string('register/edit_profile.html',request=request)
            return JsonResponse({'form':html},status=200)

        except User.DoesNotExist:
            messages.error(request, "User doesnot exist")    
            # html = render_to_string('register/edit_profile.html',request=request)
            # return JsonResponse({'form':html},status=200)
 

templates/register/ForgotPassword.html
{% extends 'header.html' %}
{% load static %}
{% block title %} Password Reset {% endblock %}
{% block content%}

<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static '/images/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static '/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}">
<!--===============================================================================================-->

	
<div class="limiter">
	<div class="container-login100">
		<div class="wrap-login100">
			<div class="login100-pic js-tilt" data-tilt>
				<img src="{% static '/images/img-01.png' %}" alt="User">
			</div>

			<form action="" method="post" class="login100-form validate-form">
				{% csrf_token %} 
					{% for message in messages %}
					<div class="container-fluid p-0">
					<div class="alert {{ message.tags }} alert-dismissible" role="alert" >
						<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
						</button>
						{{ message }}
					</div>
					</div>
					{% endfor %}
				<span class="login100-form-title">
					Password Reset
				</span>

				<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
					<input class="input100" type="text" name="email" placeholder="Email">
					<span class="focus-input100"></span>
					<span class="symbol-input100">
						<i class="fa fa-envelope" aria-hidden="true"></i>
					</span>
				</div>
				
				<div class="container-login100-form-btn">
					<button class="login100-form-btn">
						Reset my paswword
					</button>
				</div>

				<div class="text-center p-t-136">
					<a class="txt2" href="{% url 'login' %}">
						Already have an account?
						<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
					</a>
				</div>
			</form>
		</div>
	</div>
</div>
	
	

	
<!--===============================================================================================-->	
	<script src="{% static '/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static '/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static '/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static '/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static '/vendor/tilt/tilt.jquery.min.js' %}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script> 
<!--===============================================================================================-->
	<script src="{% static '/js/login.js' %}"></script>

{% endblock %} 

templates/register/PasswordResetComplete.html
{% extends 'header.html' %}
{% load static %}
{% block title %} Password reset complete {% endblock %}
{% block content%}

<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static '/images/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static '/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}">
<!--===============================================================================================-->

	
<div class="limiter">
	<div class="container-login100">
		<div class="wrap-login100 pt-5">
			<span class="login100-form-title">
				Password reset complete
			</span>
			<div class="container-login100-form-btn">
			<span>
				Your password has been set. You may go ahead and log in now.
			</span>
			</div>
			<div class="container-login100-form-btn">
            	<a href="{% url 'login' %}" class="genric-btn primary radius">Login</a>
			</div>
		</div>
	</div>
</div>
	
	

	
<!--===============================================================================================-->	
	<script src="{% static '/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static '/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static '/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static '/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static '/vendor/tilt/tilt.jquery.min.js' %}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script> 
<!--===============================================================================================-->
	<script src="{% static '/js/login.js' %}"></script>

{% endblock %} 

templates/register/PasswordResetConfirm.html
{% extends 'header.html' %}
{% load static %}
{% block title %} Password Reset Confirm {% endblock %}
{% block content%}

<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static '/images/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static '/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}">
<!--===============================================================================================-->

	
<div class="limiter">
	<div class="container-login100">
		<div class="wrap-login100">
			{% if validlink %}
			<div class="login100-pic js-tilt" data-tilt>
				<img src="{% static 'assets/img/img-01.png' %}" alt="User">
			</div>

			<form action="" method="post" class="login100-form validate-form">
				{% csrf_token %} 
				{% for field in form %}
					{% for error in field.errors %}
						<div class="container-fluid p-0">
						<div class="alert alert-danger alert-dismissible" role="alert" >
							<button type="button" class="close" data-dismiss="alert" aria-label="Close">
							<span aria-hidden="true">&times;</span>
							</button>
							{{ error }}
						</div>
						</div>
					{% endfor %}
				{% endfor %}
	
				<span class="login100-form-title">
					Password Reset
				</span>

				<div class="wrap-input100 validate-input" data-validate = "Password is required">
					<input class="input100" type="password" name="new_password1" autocomplete="new-password" required="" id="id_new_password1" placeholder="New Password">			
					<span class="focus-input100"></span>
					<span class="symbol-input100">
						<i class="fa fa-lock" aria-hidden="true"></i>
					</span>
				</div>

				<div class="wrap-input100 validate-input" data-validate = "Password is required">
					<input class="input100" type="password" name="new_password2" autocomplete="new-password" required="" id="id_new_password2" placeholder="Confirm Password">
					<span class="focus-input100"></span>
					<span class="symbol-input100">
						<i class="fa fa-lock" aria-hidden="true"></i>
					</span>
				</div>

				<div class="container-login100-form-btn">
					<input class="login100-form-btn" type="submit" value="Change password" />
				</div>
			</form>
		{% else %}
			<div class="container-login100-form-btn">
				<p>
				The password reset link was invalid, possibly because it has already been used.
				Please request a new password reset.
				</p>
			</div>
		{% endif %}
		</div>
	</div>
</div>
	
	

	
<!--===============================================================================================-->	
	<script src="{% static '/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static '/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static '/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static '/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static '/vendor/tilt/tilt.jquery.min.js' %}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script> 
<!--===============================================================================================-->
	<script src="{% static '/js/login.js' %}"></script>

{% endblock %} 

templates/register/PasswordResetDone.html
{% extends 'header.html' %}
{% load static %}
{% block title %} Password reset sent {% endblock %}
{% block content%}

<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static '/images/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static '/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}">
<!--===============================================================================================-->

	
<div class="limiter">
	<div class="container-login100">
		<div class="wrap-login100 pt-5">
			<span class="login100-form-title">
				Password reset sent
			</span>
			<span>
				We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

				If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.
			</span>
		</div>
	</div>
</div>
	
	

	
<!--===============================================================================================-->	
	<script src="{% static '/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static '/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static '/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static '/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static '/vendor/tilt/tilt.jquery.min.js' %}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script> 
<!--===============================================================================================-->
	<script src="{% static '/js/login.js' %}"></script>

{% endblock %} 

templates/register/change_password.html
{% extends 'header.html' %}
{% load static %}
{% block title %} Change Password {% endblock %}
{% block content%}

<!-- Percentage Bar Start -->
<div class="percentage m-t-100">
	<div class="progress">
		<div class="progress-bar color-1" role="progressbar" style="width: 100%"
			aria-valuenow="70" aria-valuemin="0" aria-valuemax="100"></div>
	</div>
</div>
<!-- Percentage Bar End -->

<div class="home-blog-area section-padding10 m-t-50">
	<div class="container">
		<!-- Section Tittle -->
		<div class="row">
			<div class="col-lg-12">
				<div class="section-tittle text-center m-b-50">
					<h2>User Profile</h2>
				</div>
			</div>
		</div>
		<!-- Section Tittle -->

        <div class="section-tittle text-left m-b-50">          
            <a href="{% url 'edit_profile' %}" class="btn btn-primary radius">Edit Profile</a>
            <a href="{% url 'password' %}" class="btn btn-primary radius">Change Password</a>
        </div>
        
        <div class="row">
            <!-- ============================================================== -->
            <!-- validation form -->
            <!-- ============================================================== -->
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 section-tittle  m-b-50 m-t-10">
                <div class="card">
                    <h5 class="card-header">Change Password</h5>
                    <div class="card-body">
                        <form class="needs-validation" method="POST">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 mb-2 m-t-10">
                                    <label for="validationCustom01">Old Password</label>
                                        {{form.old_password}}
                                </div>
                                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 m-b-2 m-t-10">
                                    <label for="validationCustom02">New Password</label>
                                        {{form.new_password1}}
                                </div>
								<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 m-b-2 m-t-10">
                                    <label for="validationCustom02">Confirm Password</label>
                                        {{form.new_password2}}
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 m-b-2 m-t-10">
                                    <button class="btn btn-primary e-large" type="submit">Change Password</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- end validation form -->
            <!-- ============================================================== -->
        </div>
    </div>
</div> 
<!-- Form End -->

{% endblock %}

templates/register/login.html
{% extends 'header.html' %}
{% load static %}
{% block title %} Sign In {% endblock %}
{% block content%}

<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static '/images/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static '/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/css/utils.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}">
<!--===============================================================================================-->

	
<div class="limiter">
	<div class="container-login100">
		<div class="wrap-login100">
			<div class="login100-pic js-tilt" data-tilt>
				<img src="{% static '/images/img-01.png' %}" alt="User">
			</div>

			<form action="login" method="post" class="login100-form validate-form">
				{% csrf_token %} 
					{% for message in messages %}
					<div class="container-fluid p-0">
					<div class="alert {{ message.tags }} alert-dismissible" role="alert" >
						<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
						</button>
						{{ message }}
					</div>
					</div>
					{% endfor %}
				<span class="login100-form-title">
					Member Login
				</span>

				<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
					<input class="input100" type="text" name="username" placeholder="Username/Email">
					<span class="focus-input100"></span>
					<span class="symbol-input100">
						<i class="fa fa-envelope" aria-hidden="true"></i>
					</span>
				</div>

				<div class="wrap-input100 validate-input" data-validate = "Password is required">
					<input class="input100" type="password" name="password" placeholder="Password">
					<span class="focus-input100"></span>
					<span class="symbol-input100">
						<i class="fa fa-lock" aria-hidden="true"></i>
					</span>
				</div>
				
				<div class="container-login100-form-btn">
					<button class="login100-form-btn">
						Login
					</button>
				</div>

				<div class="text-center p-t-136">
					<span class="txt1">
						Forgot
					</span>
					<a class="txt2" href="{% url 'reset_password' %}">
						Username / Password?
					</a>
				</div>
			</form>
		</div>
	</div>
</div>
	
	

	
<!--===============================================================================================-->	
	<script src="{% static '/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static '/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static '/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static '/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static '/vendor/tilt/tilt.jquery.min.js' %}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script> 
<!--===============================================================================================-->
	<script src="{% static '/js/login.js' %}"></script>

{% endblock %} 